service: test-service

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  localPath: '../../'
  modules:
    - serverless-step-functions
    - serverless-local-schedule
functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
          name: test-crontab
          timezone: America/New_York
      - schedule:
          rate: cron(0 5 * * ? *)
          timezone: America/New_York
      - schedule:
          rate:
            - cron(0 5 * * ? *)
            - cron(0 6 * * ? *)
          timezone: America/New_York

stepFunctions:
  stateMachines:
    hellostepfunc1:
      events:
        - schedule:
            rate: cron(0 5 * * ? *)
            enabled: true
            timezone: America/New_York
      name: myStateMachine
      definition:
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true
  validate: true
